using System;
using System.Windows.Forms;

namespace QuanLyNhaHang
{
    /// <summary>
    /// Form CSDL Firebird (SFORM): AS SO, EXTRACT(HOUR FROM BATDAU) || ':' || EXTRACT(MINUTE FROM BATDAU) AS BATDAU, EXTRACT(HOUR FROM KETTHUC) || ':' || EXTRACT(MINUTE FROM KETTHUC) AS KETTHUC, (SELECT NAME FROM DBAN WHERE
    /// ID: 
    /// </summary>
    public partial class FormASSOEXTRACTHOURFROMBATDAUEXTRACTMINUTEFROMBATDAUASBATDAUEXTRACTHOURFROMKETTHUCEXTRACTMINUTEFROMKETTHUCASKETTHUCSELECTNAMEFROMDBANWHERE : Form
    {
        public string SFormId { get; } = "";
        public string SFormTitle { get; } = "AS SO, EXTRACT(HOUR FROM BATDAU) || ':' || EXTRACT(MINUTE FROM BATDAU) AS BATDAU, EXTRACT(HOUR FROM KETTHUC) || ':' || EXTRACT(MINUTE FROM KETTHUC) AS KETTHUC, (SELECT NAME FROM DBAN WHERE";
        public string SFormClassName { get; } = "FormASSOEXTRACTHOURFROMBATDAUEXTRACTMINUTEFROMBATDAUASBATDAUEXTRACTHOURFROMKETTHUCEXTRACTMINUTEFROMKETTHUCASKETTHUCSELECTNAMEFROMDBANWHERE";

        public FormASSOEXTRACTHOURFROMBATDAUEXTRACTMINUTEFROMBATDAUASBATDAUEXTRACTHOURFROMKETTHUCEXTRACTMINUTEFROMKETTHUCASKETTHUCSELECTNAMEFROMDBANWHERE()
        {
            InitializeComponent();
        }
    }
}
